CREATE TABLE QUESTIONS(
QUESTION_NO INT (10) NOT NULL AUTO_INCREMENT PRIMARY KEY,
QUESTION VARCHAR(255) NOT NULL,
OPTION_A VARCHAR(255) NOT NULL,
OPTION_B VARCHAR(255) NOT NULL,
OPTION_C VARCHAR(255) NOT NULL,
OPTION_D VARCHAR(255) NOT NULL,
CORRECT_ANSWER VARCHAR(255) NOT NULL );